# App routing
app:
    resource: "@AppBundle/Controller/"
    type:     annotation

# FOSUser routing
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

# FOSJs routing
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

# SgDataTables routing
sg_datatables_bundle:
    resource: "@SgDatatablesBundle/Controller/"
    type:     annotation