services:
    # Event
    app.event_listener.login:
        class: AppBundle\EventListener\LoginListener
        arguments: 
            - '@security.authorization_checker'
            - "@router"
            - "@event_dispatcher"
            - "@session"
        tags:
            - { name: kernel.event_listener, event: security.interactive_login, method: onSecurityInteractiveLogin }

    # Form
    app.form.extention.field_type_help:
        class: AppBundle\Form\Extension\FieldTypeHelpExtension
        tags:
            - { name: form.type_extension, extended_type: Symfony\Component\Form\Extension\Core\Type\FormType }
    app.form.type.dashboard_filter:
        class: AppBundle\Form\Type\Filter\DashboardFilterType
        arguments: ['@security.authorization_checker']
        tags:
            - { name: form.type }

    # Menu
    app.menu.builder:
        class: AppBundle\Menu\MenuBuilder
        arguments:
            - "@knp_menu.factory"
            - "@security.authorization_checker"

    app.menu.backend:
        class: Knp\Menu\MenuItem
        factory: ["@app.menu.builder", createMainMenu]
        arguments:
            - "@request_stack"
        tags:
            - { name: knp_menu.menu, alias: main }

    # Statistic
    app.statistic.project:
        class: AppBundle\Statistic\ProjectStatistic
        arguments: 
            - "@doctrine.orm.entity_manager"

    app.statistic.tag:
        class: AppBundle\Statistic\TagStatistic
        arguments: 
            - "@doctrine.orm.entity_manager"

    app.statistic.user:
        class: AppBundle\Statistic\UserStatistic
        arguments: 
            - "@doctrine.orm.entity_manager"

    # Datatable
    app.datatable.project:
        class: AppBundle\Datatables\ProjectDatatable
        parent: sg_datatables.datatable.abstract
    app.datatable.tag:
        class: AppBundle\Datatables\TagDatatable
        parent: sg_datatables.datatable.abstract
    app.datatable.task:
        class: AppBundle\Datatables\TaskDatatable
        parent: sg_datatables.datatable.abstract
    app.datatable.user:
        class: AppBundle\Datatables\UserDatatable
        parent: sg_datatables.datatable.abstract